name: Deploy Coti-Blog-Filesystem

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Validate JSON structure
        run: |
          # Validate that the JSON file exists and is valid
          if [ ! -f "files/blog_articles.json" ]; then
            echo "Error: blog_articles.json not found"
            exit 1
          fi

          # Validate JSON syntax (using Node.js)
          node -e "JSON.parse(require('fs').readFileSync('files/blog_articles.json', 'utf8'))"

          echo "✅ JSON validation passed"

      # Add your deployment steps here
      - name: Deploy
        run: |
          echo "Add your deployment logic here"
          # Example: sync to S3, upload to server, etc.
